### ISSUE TITLE
user-provided variables (branch feature/user_vars) -- vote for inclusion in master

### ISSUE THREAD

**Issue by xorpaul** [go-gcfg/gcfg#8]
Hello there,

do you plan to also migrate the feature branch `user_vars` from code.google.com to this repository?

I'm currently depending on this feature branch for a project.

A merge of the feature branch to master would be even better! :)

**Comment by speter** [comment]
tl;dr: `feature/user_vars` now available. People who need this please "thumbs-up" this comment to vote to have it merged into master.

Full comment:

Thanks for the heads up, I kind of forgot about migrating that branch. It's there now. I will merge the changes in master into the feature branch.

I've been hesitant about merging the feature into master because it adds noticeable complexity for what seems to be a niche feature. But I can be convinced that it's worth the complexity by having interested people vote (thumbs-up this comment) or share their use cases (ideally with source links).

**Comment by speter** [comment]
Moved to PR #9; please discuss there further.
